[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
actuate = { git = "https://github.com/actuate-rs/actuate", features = ["animation", "ecs"] }
bevy = "0.15.0-rc.3"
tokio = { version = "1.41.1", features = ["sync"] }
voxy = { git = "https://github.com/matthunz/voxy" }
